import { StyleSheet } from "react-native";
import { brand } from "../../theme/brand";

export const submitTaskStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 8, 20, 0.84)",
    justifyContent: "center",
    padding: 16,
  },
  sheet: {
    maxHeight: "88%",
    borderRadius: brand.radiusLg,
    borderWidth: 1,
    borderColor: brand.borderEmphasis,
    backgroundColor: brand.bgElevated,
    overflow: "hidden",
  },
  head: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: brand.borderMuted,
  },
  headText: { flex: 1, minWidth: 0, gap: 4 },
  title: {
    fontSize: 17,
    fontFamily: brand.fontBodyBold,
    fontWeight: "700",
    color: brand.text,
  },
  aside: {
    fontSize: 13,
    fontFamily: brand.fontBodySemi,
    fontWeight: "600",
    color: brand.gold200,
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: brand.radiusSm,
    borderWidth: 1,
    borderColor: brand.border,
    alignItems: "center",
    justifyContent: "center",
  },
  scroll: { flexGrow: 0 },
  body: { padding: 20, gap: 8 },
  hint: {
    fontSize: 13,
    lineHeight: 20,
    fontFamily: brand.fontBody,
    color: brand.textSecondary,
    marginBottom: 8,
  },
  label: {
    marginTop: 8,
    fontSize: 12,
    fontFamily: brand.fontBodySemi,
    fontWeight: "600",
    color: brand.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  optional: {
    fontSize: 11,
    textTransform: "none",
    letterSpacing: 0,
    color: brand.textMuted,
  },
  dropzone: {
    minHeight: 72,
    borderRadius: brand.radiusSm,
    borderWidth: 1,
    borderColor: brand.border,
    backgroundColor: "rgba(0,0,0,0.25)",
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 4,
  },
  dropzoneFilled: {
    borderColor: brand.borderEmphasis,
    backgroundColor: "rgba(212,168,67,0.08)",
  },
  dropRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dropName: {
    flex: 1,
    color: brand.gold200,
    fontFamily: brand.fontBodySemi,
    fontWeight: "600",
    fontSize: 14,
  },
  dropHint: {
    fontSize: 12,
    fontFamily: brand.fontBody,
    color: brand.textMuted,
  },
  input: {
    minHeight: 44,
    borderRadius: brand.radiusSm,
    borderWidth: 1,
    borderColor: brand.border,
    backgroundColor: "rgba(0,0,0,0.25)",
    color: brand.text,
    paddingHorizontal: 16,
    fontFamily: brand.fontBody,
    fontSize: 14,
  },
  textarea: { minHeight: 96, paddingVertical: 12 },
  error: {
    color: brand.danger,
    fontFamily: brand.fontBodySemi,
    fontWeight: "600",
    fontSize: 12,
  },
  actions: {
    marginTop: 16,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  btnOutline: {
    flex: 1,
    minHeight: 44,
    borderRadius: brand.radiusSm,
    borderWidth: 1,
    borderColor: brand.borderEmphasis,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  btnOutlineText: {
    color: brand.textSecondary,
    fontFamily: brand.fontBodySemi,
    fontWeight: "600",
    fontSize: 13,
  },
  btnGold: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: brand.gold,
    borderRadius: brand.radiusSm,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  actionGold: { flex: 1.2, minHeight: 44 },
  btnGoldText: {
    color: brand.bg,
    fontFamily: brand.fontBodyBold,
    fontWeight: "700",
    fontSize: 14,
  },
  disabled: { opacity: 0.5 },
  dryRunRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginTop: 10,
    marginBottom: 4,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: brand.border,
    backgroundColor: "rgba(0,0,0,0.22)",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  checkboxOn: {
    borderColor: brand.gold400,
    backgroundColor: "rgba(212,168,67,0.25)",
  },
  checkboxMark: {
    color: brand.gold200,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 14,
  },
  dryRunText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: brand.fontBody,
    color: brand.textSecondary,
  },
  processing: {
    alignItems: "center",
    gap: 12,
    paddingVertical: 16,
  },
  processingTitle: {
    fontSize: 17,
    fontFamily: brand.fontBodyBold,
    fontWeight: "700",
    color: brand.text,
    textAlign: "center",
  },
  result: {
    alignItems: "center",
    gap: 12,
    paddingVertical: 8,
  },
  resultIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
    borderWidth: 1,
  },
  resultIconOk: {
    backgroundColor: "rgba(63,185,80,0.12)",
    borderColor: "rgba(63,185,80,0.35)",
  },
  resultIconFail: {
    backgroundColor: "rgba(248,81,73,0.12)",
    borderColor: "rgba(248,81,73,0.35)",
  },
  resultTitle: {
    fontSize: 17,
    fontFamily: brand.fontBodyBold,
    fontWeight: "700",
    color: brand.text,
    textAlign: "center",
  },
  resultHint: {
    fontSize: 13,
    lineHeight: 20,
    fontFamily: brand.fontBody,
    color: brand.textSecondary,
    textAlign: "center",
    maxWidth: 280,
  },
});
